#!/bin/bash

if ! make -k all
then
  fail="$fail build"
else
  pass="$pass build"
fi

for t in bin/$(uname -s)-$(uname -m)/test_*
do
  if ! "$t"
  then
      fail="$fail $t"
  else
      pass="$pass $t"
  fi
done
echo "passed tests:$pass"
if [ "$fail" != "" ]
then
  echo "failed tests:$fail"
  exit 1
fi
